### ISSUE TITLE
DNS spoofing

### ISSUE THREAD

**Issue by sweetcharity** [davinerd/mitmnbdf#2]
Is it possible to run mitmnbdf inline script along with mitmproxy's dns spoofing inline script - https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py ? Both scripts work ok separately, but doesn't work when running together in my case.

**Comment by davinerd** [comment]
Can you please paste here the error (if any)?

Assuming you're using the same port as in the DNS spoofing example (443) it may create a collision, i.e. libmitmproxy doesn't know if redirect traffic on port 443 to dns_spoofing or mitmnbdf.

Can you try to change mitmnbdf's ssl port to test?

Thank you

**Comment by sweetcharity** [comment]
mitmproxy --host -s dns_spoofing.py -R http://url_of_site/ -s "mitmnbdf_inline.py mitmnbdf.cfg"
I use default 8080 port for mitmproxy and I don't specify any port for dns_spoofing.py (where? why?)

When I visit http://url_of_site/ mitmproxy crashed:

"mitmnbdf_inline.py mitmnbdf.cfg"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/__init__.py", line 499, in run
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/window.py", line 38, in keypress
    k = super(self.__class__, self).keypress(size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 377, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 1001, in keypress
    return actual_key(self._keypress_down((maxcol, maxrow)))
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 1119, in _keypress_down
    widget, pos = self.body.get_next(pos)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 279, in get_next
    f = ConnectionItem(self.master, self.state, f, False) if f else None
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 106, in __init__
    w = self.get_text()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/flowlist.py", line 114, in get_text
    marked=self.state.flow_marked(self.flow)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/console/common.py", line 399, in format_flow
    contentdesc = netlib.utils.pretty_size(len(f.response.content))
TypeError: object of type 'HTTPFlow' has no len()

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

**Comment by sweetcharity** [comment]
same error occurs if I paste the code of 'dns_spoofing.py" in "mitmnbdf_inline.py" and execute 

mitmproxy --host -R http://url_of_site/ -s "mitmnbdf_inline.py mitmnbdf.cfg"

**Comment by sweetcharity** [comment]
more info:

mitmproxy works perfectly when run "mitmproxy --host --spoof" in my scenario (DNS spoofing)

But it doesn't work  in transparent mode - "ProxyError(NetLibError('Error connecting to "10.0.1.3": [Errno 111] Connection refused',),)"

when I try 

mitmproxy --host --spoof -s "mitmnbdf_inline.py mitmnbdf.cfg"

mitmproxy crashes

**Comment by davinerd** [comment]
That's interesting: based on the error you posted, it doesn't seem an issue related to mitmnbdf but rather to mitmproxy core.

I'll try to reproduce your bug in the next days and will let you know, thanks.

**Comment by sweetcharity** [comment]
Maximilian Hils from mitmproxy wrote "The inline script looks wrong: flow.response.content = mitmnbdf.flow. I don't think this is a bug in mitmproxy."

https://github.com/mitmproxy/mitmproxy/issues/1068

**Comment by davinerd** [comment]
Thanks for digging into it. Unfortunately I didn't had the time to do some tests - will do in the next few days and will fix it.
